# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    images.planning: '%kernel.project_dir%/public/images/planning.png'
    images.thumbnail: '%kernel.project_dir%/public/images/thumbnail.png'
    upload_dir: '%kernel.project_dir%/public/uploads'
    fonts.thunder: '%kernel.project_dir%/public/fonts/Thunder-BoldLC.ttf'
    fonts.monument: '%kernel.project_dir%/public/fonts/MonumentExtended-Regular.otf'
    intervention.driver: imagick
    container.dumper.inline_factories: true
    timezone: '%env(APP_TIMEZONE)%'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            string $planningImage: '%images.planning%'
            string $thumbnailImage: '%images.thumbnail%'
            array $fonts:
                thunder: '%fonts.thunder%'
                monument: '%fonts.monument%'
            string $uploadDir: '%upload_dir%'
            iterable $clients: !tagged_iterator { tag: 'app.oauth.client', default_index_method: 'getName' }

    _instanceof:
        App\OAuth\ClientInterface:
            tags: ['app.oauth.client']

        App\Doctrine\Type\AbstractEnumType:
            tags:
                - { name: 'app.doctrine_enum_type' }

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/DataCollector/'

    Intervention\Image\ImageManager:
        factory: [App\ImageManager\ImageManagerFactory, 'create']
        arguments: ['%intervention.driver%']

    App\OAuth\GoogleClient:
        calls:
            - [setDeveloperKey, ['%env(GOOGLE_API_KEY)%']]
            - [setClientId, ['%env(GOOGLE_CLIENT_ID)%']]
            - [setClientSecret, ['%env(GOOGLE_CLIENT_SECRET)%']]
            - [setScopes, ['https://www.googleapis.com/auth/youtube']]
            - [setAccessType, ['offline']]
            - [setApprovalPrompt, ['force']]
            - [setIncludeGrantedScopes, [true]]
            - [initRedirectUri, ['%env(APP_HOST)%', '@router']]

    App\OAuth\TwitchClient:
        calls:
            - [setClientId, ['%env(TWITCH_CLIENT_ID)%']]
            - [setClientSecret, ['%env(TWITCH_CLIENT_SECRET)%']]
            - [setScopes, [['chat:read', 'chat:edit']]]
            - [initRedirectUri, ['%env(APP_HOST)%', '@router']]
